= PickPick(a.k.a 줍줍) API Document
pickpick team
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[introduction]]
== 소개

줍줍 API 문서 입니다.

== 서비스환경

해당 API서비스의 서버 도메인 환경은 다음과 같습니다.

== Domain

|===
| 환경 | URI

| 개발서버
| `????`

| 운영서버
| `????`
|===

= 채널
== 채널 API
=== 전체 채널 조회 API

operation::channel-controller-test/find-all[snippets='http-request,request-headers,http-response,response-fields']


== 채널 구독 API

=== 구독중인 채널 조회 API

operation::channel-subscription-controller-test/find-all-subscribed-channel[snippets='http-request,request-headers,http-response,response-fields']

=== 채널 구독 API

operation::channel-subscription-controller-test/subscribe-channel[snippets='http-request,request-headers,request-fields,http-response']

=== 채널 구독 취소 API

operation::channel-subscription-controller-test/unsubscribe-channel[snippets='http-request,request-headers,request-parameters,http-response']

=== 구독 채널 순서 변경 API

operation::channel-subscription-controller-test/update-order-of-subscribed-channel[snippets='http-request,request-headers,request-fields,http-response']

= 메시지
== 메시지 API
=== 각 검색조건을 포함한 메시지 조회 API

자세한 예시는 https://github.com/woowacourse-teams/2022-pickpick/wiki/메시지-조회-API-사용법에서 확인

operation::message-controller-test/find-all-message-with-condition[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

== 북마크 API

=== 북마크 조회 API

operation::bookmark-controller-test/find[snippets='http-request,request-headers,http-response,response-fields']

=== 북마크 추가 API

operation::bookmark-controller-test/save[snippets='http-request,request-headers,request-fields,http-response']

=== 북마크 삭제 API

operation::bookmark-controller-test/delete[snippets='http-request,request-headers,request-parameters,http-response']

== 리마인더 API

=== 리마인더 목록 조회 API

operation::reminder-controller-test/find[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

=== 리마인더 단건 조회 API

operation::reminder-controller-test/find-one[snippets='http-request,request-headers,request-parameters,http-response,response-fields']

=== 리마인더 추가 API

operation::reminder-controller-test/save[snippets='http-request,request-headers,request-fields,http-response']

=== 리마인더 삭제 API

operation::reminder-controller-test/delete[snippets='http-request,request-headers,request-parameters,http-response']

=== 리마인더 수정 API

operation::reminder-controller-test/update[snippets='http-request,request-headers,request-fields,http-response']
