name: 줍줍 백엔드 SonarQube 정적 분석
on:
  push:
    branches:
      - main
      - release/*
      - develop
    paths: 'backend/**'
  pull_request:
    branches:
      - main
      - release/*
      - develop
    paths: 'backend/**'

defaults:
  run:
    working-directory: backend

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: 리포지토리를 가져옵니다
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SUBMODULE_TOKEN }}
          submodules: recursive

      - name: JDK 11을 설치합니다
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: TimeZone을 Asia/Seoul로 설정합니다
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Seoul

      - name: Gradle 명령 실행을 위한 권한을 부여합니다
        run: chmod +x gradlew

      - name: 정적 분석 결과를 SonarQube 서버로 전송합니다
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./gradlew build sonarqube --info
