name: Rich Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.RICH_GITHUB_TOKEN }}
          submodules: recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set Timezone as Asia/Seoul
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Seoul

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ./backend

      - name: Build with Gradle
        run: ./gradlew clean build
        working-directory: ./backend

      - name: build result to slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Github Action Test by Richie
          fields: repo, message, commit, author, action, eventName, ref, workflow, job, took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
